<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-S1PH1A1" name="test.Basic3" tests="8" failures="1" timestamp="29 Sep 2018 10:33:17 GMT" time="0.017" errors="0">
  <testcase name="MobileupdatecarLoan" time="0.001" classname="test.Basic3"/>
  <testcase name="MobileupdatecarLoan" time="0.001" classname="test.Basic3"/>
  <testcase name="MobileLogincarLoan" time="0.002" classname="test.Basic3"/>
  <testcase name="WEbloginCarLoan" time="0.001" classname="test.Basic3"/>
  <testcase name="MobilesingnincarLoan" time="0.001" classname="test.Basic3"/>
  <testcase name="LoginAPIcarLoan" time="0.005" classname="test.Basic3"/>
  <testcase name="MobilecovercarLoan" time="0.005" classname="test.Basic3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at test.Basic3.MobilecovercarLoan(Basic3.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- MobilecovercarLoan -->
  <testcase name="MobileupdatecarLoan" time="0.001" classname="test.Basic3"/>
</testsuite> <!-- test.Basic3 -->
